import {supabase} from './supabase';

export type Conversation={id:string;name:string;message:string;time:string;online?:boolean;unread?:number};
export type UserProfile={id:string;display_name:string;username:string|null;last_seen:string|null};

export async function loadConversations():Promise<Conversation[]>{const {data:{user},error:u}=await supabase.auth.getUser();if(u)throw u;if(!user)return[];const {data:members,error:m}=await supabase.from('conversation_members').select('conversation_id').eq('user_id',user.id);if(m)throw m;const result:Conversation[]=[];for(const row of members??[]){const {data:c}=await supabase.from('conversations').select('id,title,is_group,created_at').eq('id',row.conversation_id).maybeSingle();if(!c)continue;const {data:others}=await supabase.from('conversation_members').select('user_id').eq('conversation_id',c.id).neq('user_id',user.id).limit(1);const otherId=others?.[0]?.user_id;const profile=otherId?(await supabase.from('profiles').select('display_name,last_seen').eq('id',otherId).maybeSingle()).data:null;const last=(await supabase.from('messages').select('body,created_at').eq('conversation_id',c.id).order('created_at',{ascending:false}).limit(1).maybeSingle()).data;result.push({id:c.id,name:c.is_group?(c.title||'Group'):(profile?.display_name||'GG User'),message:last?.body||'No messages yet',time:last?.created_at?new Date(last.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'',online:!!profile?.last_seen&&Date.now()-new Date(profile.last_seen).getTime()<120000});}return result.sort((a,b)=>b.time.localeCompare(a.time));}

export async function ensureProfile(displayName:string){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from('profiles').upsert({id:user.id,display_name:displayName.trim()||'GG User'},{onConflict:'id'});if(error)throw error;}

export async function searchUsers(query:string){const {data:{user}}=await supabase.auth.getUser();if(!user)return[];const q=query.trim();if(!q)return[];const {data,error}=await supabase.from('profiles').select('id,display_name,username,last_seen').neq('id',user.id).or(`display_name.ilike.%${q}%,username.ilike.%${q}%`).limit(20);if(error)throw error;return(data??[]) as UserProfile[];}

export async function createDirectConversation(otherUserId:string){const {data:{user},error}=await supabase.auth.getUser();if(error)throw error;if(!user)throw new Error('You must be signed in');if(user.id===otherUserId)throw new Error('You cannot message yourself');const {data:mine}=await supabase.from('conversation_members').select('conversation_id').eq('user_id',user.id);for(const row of mine??[]){const {data:other}=await supabase.from('conversation_members').select('user_id').eq('conversation_id',row.conversation_id).eq('user_id',otherUserId).maybeSingle();if(other){const {data:c}=await supabase.from('conversations').select('id').eq('id',row.conversation_id).eq('is_group',false).maybeSingle();if(c)return c.id as string;}}const {data:c,error:cError}=await supabase.from('conversations').insert({is_group:false}).select('id').single();if(cError)throw cError;const {error:mError}=await supabase.from('conversation_members').insert([{conversation_id:c.id,user_id:user.id},{conversation_id:c.id,user_id:otherUserId}]);if(mError)throw mError;return c.id as string;}
