import React,{useCallback,useState}from'react';
import{ActivityIndicator,Alert,FlatList,Pressable,SafeAreaView,StyleSheet,Text,View}from'react-native';
import{supabase}from'../lib/supabase';
import{Call,createCall}from'../lib/calls';

type Row=Call&{peerName:string;peerId:string};

export default function CallHistoryScreen({onBack}:{onBack:()=>void}){
 const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data,error}=await supabase.from('calls').select('*').or(`caller_id.eq.${user.id},callee_id.eq.${user.id}`).order('created_at',{ascending:false});if(error)throw error;const calls=(data||[])as Call[];const ids=[...new Set(calls.map(c=>c.caller_id===user.id?c.callee_id:c.caller_id))];let names:Record<string,string>={};if(ids.length){const{data:p}=await supabase.from('profiles').select('id,display_name').in('id',ids);for(const x of p||[])names[x.id]=x.display_name||'GG User'}setRows(calls.map(c=>{const peerId=c.caller_id===user.id?c.callee_id:c.caller_id;return{...c,peerId,peerName:names[peerId]||'GG User'}}));}catch(e){Alert.alert('Call history unavailable',String(e))}finally{setLoading(false)}},[]);
 React.useEffect(()=>{load()},[load]);
 async function callAgain(r:Row){try{const c=await createCall(r.peerId,r.type);Alert.alert('Calling',`Calling ${r.peerName}…`);void c}catch(e){Alert.alert('Call failed',String(e))}}
 function icon(r:Row){if(r.status==='rejected')return'↙';if(r.callee_id&&r.status==='ended'&&r.callee_id===r.peerId)return'↙';return r.caller_id===r.peerId?'↗':'↙'}
 function label(r:Row){if(r.status==='rejected')return'Missed / rejected';if(r.status==='ringing')return'Unanswered';if(r.caller_id===r.peerId)return'Incoming';return'Outgoing'}
 return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={onBack}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>Call history</Text><Pressable onPress={load}><Text style={s.refresh}>↻</Text></Pressable></View>{loading?<View style={s.center}><ActivityIndicator size="large" color="#00a884"/></View>:<FlatList data={rows} keyExtractor={x=>x.id} contentContainerStyle={rows.length?undefined:s.emptyList} ListEmptyComponent={<View style={s.center}><Text style={s.emptyIcon}>☎</Text><Text style={s.emptyTitle}>No call history</Text><Text style={s.muted}>Your voice and video calls will appear here.</Text></View>} renderItem={({item:r})=><View style={s.row}><View style={s.avatar}><Text style={s.avatarText}>{r.peerName[0]?.toUpperCase()}</Text></View><View style={s.body}><Text style={s.name}>{r.peerName}</Text><Text style={[s.meta,{color:r.status==='rejected'?'#e53935':'#667781'}]}>{icon(r)} {label(r)} • {new Date(r.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</Text></View><Text style={s.type}>{r.type==='video'?'▣':'☎'}</Text><Pressable onPress={()=>callAgain(r)} style={s.callBtn}><Text style={s.callText}>☎</Text></Pressable></View>}/>}</SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f0f2f5'},header:{height:62,backgroundColor:'#075e54',flexDirection:'row',alignItems:'center',paddingHorizontal:14},back:{color:'#fff',fontSize:40,lineHeight:44,width:42},title:{color:'#fff',fontSize:20,fontWeight:'900',flex:1},refresh:{color:'#fff',fontSize:27},row:{minHeight:76,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',paddingHorizontal:14,borderBottomWidth:1,borderBottomColor:'#edf0f2'},avatar:{width:50,height:50,borderRadius:25,backgroundColor:'#d9fdd3',alignItems:'center',justifyContent:'center'},avatarText:{color:'#075e54',fontSize:19,fontWeight:'900'},body:{flex:1,marginLeft:13},name:{fontSize:16,fontWeight:'800',color:'#111b21'},meta:{fontSize:13,marginTop:5},type:{fontSize:20,color:'#075e54',marginHorizontal:10},callBtn:{width:42,height:42,borderRadius:21,backgroundColor:'#00a884',alignItems:'center',justifyContent:'center'},callText:{color:'#fff',fontSize:20},center:{flex:1,alignItems:'center',justifyContent:'center',padding:30},emptyList:{flex:1},emptyIcon:{fontSize:50,color:'#075e54'},emptyTitle:{fontSize:20,fontWeight:'900',color:'#111b21',marginTop:12},muted:{color:'#667781',marginTop:6,textAlign:'center'}});