import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class AuthPage extends StatefulWidget { const AuthPage({super.key}); @override State<AuthPage> createState()=>_AuthPageState(); }
class _AuthPageState extends State<AuthPage> {
  bool signup=false,busy=false; final name=TextEditingController(),email=TextEditingController(),password=TextEditingController();
  void snack(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
  Future<void> submit() async { if(email.text.trim().isEmpty||password.text.isEmpty||(signup&&name.text.trim().isEmpty)){snack('Complete all required fields.');return;} setState(()=>busy=true); try { if(signup){final r=await Supabase.instance.client.auth.signUp(email:email.text.trim(),password:password.text,data:{'display_name':name.text.trim()});if(r.session==null)snack('Check your email to confirm your account.');}else{await Supabase.instance.client.auth.signInWithPassword(email:email.text.trim(),password:password.text);}}catch(e){snack(e.toString());}finally{if(mounted)setState(()=>busy=false);}}
  Future<void> reset() async {if(email.text.trim().isEmpty){snack('Enter your email first.');return;}try{await Supabase.instance.client.auth.resetPasswordForEmail(email.text.trim());snack('Password reset email sent.');}catch(e){snack(e.toString());}}
  @override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(children:[Container(width:78,height:78,decoration:BoxDecoration(color:const Color(0xff111827),borderRadius:BorderRadius.circular(24)),child:const Center(child:Text('GG',style:TextStyle(color:Colors.white,fontSize:30,fontWeight:FontWeight.w900)))),const SizedBox(height:22),Text(signup?'Create your account':'Welcome back',style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(signup?'Join GG Messenger and stay connected.':'Sign in to continue your conversations.',textAlign:TextAlign.center,style:const TextStyle(color:Color(0xff667085))),const SizedBox(height:25),if(signup)field(name,'Display name'),field(email,'Email address',type:TextInputType.emailAddress),field(password,'Password',obscure:true),if(!signup)Align(alignment:Alignment.centerRight,child:TextButton(onPressed:reset,child:const Text('Forgot password?'))),const SizedBox(height:8),SizedBox(width:double.infinity,height:54,child:FilledButton(onPressed:busy?null:submit,child:Text(busy?'Please wait...':signup?'Create account':'Sign in'))),TextButton(onPressed:()=>setState(()=>signup=!signup),child:Text(signup?'Already have an account? Sign in':'New to GG? Create an account'))]))));
  Widget field(TextEditingController c,String hint,{bool obscure=false,TextInputType? type})=>Padding(padding:const EdgeInsets.only(bottom:11),child:TextField(controller:c,obscureText:obscure,keyboardType:type,decoration:InputDecoration(hintText:hint,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(15)))));
}
