import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class CommunityPage extends StatefulWidget { const CommunityPage({super.key}); @override State<CommunityPage> createState()=>_CommunityPageState(); }
class _CommunityPageState extends State<CommunityPage>{
 final sb=Supabase.instance.client; List<Map<String,dynamic>> groups=[]; bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load() async { try { final u=sb.auth.currentUser; if(u==null)return; final ms=await sb.from('conversation_members').select('conversation_id').eq('user_id',u.id); final out=<Map<String,dynamic>>[]; for(final m in ms){ final c=await sb.from('conversations').select('id,title,is_group').eq('id',m['conversation_id']).eq('is_group',true).maybeSingle(); if(c!=null)out.add(Map<String,dynamic>.from(c)); } if(mounted)setState(()=>groups=out); }catch(_){}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> createGroup() async { final ctl=TextEditingController(); await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Create community group'),content:TextField(controller:ctl,decoration:const InputDecoration(labelText:'Group name')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:() async {final name=ctl.text.trim();if(name.isEmpty)return;try{final u=sb.auth.currentUser!;final c=await sb.from('conversations').insert({'title':name,'is_group':true}).select('id').single();await sb.from('conversation_members').insert({'conversation_id':c['id'],'user_id':u.id});if(context.mounted)Navigator.pop(context);load();}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}},child:const Text('Create'))]));ctl.dispose();}
 Future<void> invite(String id,String name) async {try{final u=sb.auth.currentUser!;final token='${u.id.substring(0,8)}_${DateTime.now().millisecondsSinceEpoch}';await sb.from('conversation_invites').insert({'conversation_id':id,'created_by':u.id,'token':token});final link='gg://invite/$token';if(!mounted)return;showDialog(context:context,builder:(_)=>AlertDialog(title:Text('Invite $name'),content:Column(mainAxisSize:MainAxisSize.min,children:[QrImageView(data:link,size:190),const SizedBox(height:12),SelectableText(link)]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Close'))]));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Invite failed: $e')));}}
 Future<void> join() async {final ctl=TextEditingController();await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Join with invite'),content:TextField(controller:ctl,decoration:const InputDecoration(hintText:'Paste GG invite link or token')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:() async {try{var token=ctl.text.trim();if(token.contains('/'))token=token.split('/').last;await sb.rpc('join_conversation_by_invite',params:{'invite_token':token});if(context.mounted)Navigator.pop(context);load();}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Join failed: $e')));}},child:const Text('Join'))]));ctl.dispose();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Communities'),actions:[IconButton(onPressed:createGroup,icon:const Icon(Icons.add)),IconButton(onPressed:join,icon:const Icon(Icons.link))]),body:loading?const Center(child:CircularProgressIndicator()):groups.isEmpty?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.groups_outlined,size:64),const SizedBox(height:12),const Text('Your communities',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:12),FilledButton(onPressed:createGroup,child:const Text('Create community'))])):ListView.builder(padding:const EdgeInsets.all(12),itemCount:groups.length,itemBuilder:(_,i){final g=groups[i];return Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.groups)),title:Text('${g['title']??'Community'}'),subtitle:const Text('Announcements • Groups'),trailing:IconButton(onPressed:()=>invite(g['id'].toString(),'${g['title']??'Community'}'),icon:const Icon(Icons.qr_code_2))));}));
}
