import React,{useEffect,useState}from'react';
import{FlatList,Modal,Pressable,SafeAreaView,StatusBar,StyleSheet,Text,TextInput,View}from'react-native';
import{openCommunity}from'./communityNavigation';
import{supabase}from'./lib/supabase';

const BG='#061015',CARD='#0d171c',TEXT='#f4f7f8',MUTED='#8ea0ad',GREEN='#00e676';
type Community={id:string;name:string;description:string};

export default function CommunityHome({onBack}:{onBack:()=>void}){
 const[create,setCreate]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState(''),[communities,setCommunities]=useState<Community[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{const{data:me}=await supabase.auth.getUser();if(!me.user)return;const{data:members}=await supabase.from('conversation_members').select('conversation_id').eq('user_id',me.user.id);const ids=(members||[]).map(x=>x.conversation_id);if(!ids.length){setCommunities([]);return}const{data}=await supabase.from('conversations').select('id,title').in('id',ids).eq('is_group',true).order('created_at',{ascending:false});setCommunities((data||[]).map(x=>({id:x.id,name:x.title||'GG Community',description:'Community on GG'})));};
 useEffect(()=>{load()},[]);
 const createCommunity=async()=>{const clean=name.trim();if(!clean){setError('Enter a community name');return}setBusy(true);setError('');try{const{data:me}=await supabase.auth.getUser();if(!me.user)throw new Error('Please sign in again');const{data:c,error:e}=await supabase.from('conversations').insert({title:clean,is_group:true}).select('id,title').single();if(e)throw e;const{error:meError}=await supabase.from('conversation_members').insert({conversation_id:c.id,user_id:me.user.id});if(meError)throw meError;setCommunities(v=>[{id:c.id,name:c.title||clean,description:description.trim()||'Community on GG'},...v]);setName('');setDescription('');setCreate(false)}catch(e:any){setError(e?.message||'Could not create community')}finally{setBusy(false)}};
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={BG}/><View style={s.header}><Pressable onPress={onBack}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>Communities</Text><View style={{width:42}}/></View>
 <View style={s.hero}><View style={s.heroIcon}><Text style={s.heroIconText}>♧</Text></View><Text style={s.heroTitle}>Build your community</Text><Text style={s.heroText}>Create a place for people with shared interests to connect, chat and share updates.</Text><Pressable style={s.createButton} onPress={()=>setCreate(true)}><Text style={s.createText}>＋ Create community</Text></Pressable></View>
 <View style={s.sectionRow}><Text style={s.section}>Your communities</Text><Text style={s.count}>{communities.length}</Text></View>
 <FlatList data={communities} keyExtractor={x=>x.id} contentContainerStyle={s.list} ListEmptyComponent={<View style={s.empty}><Text style={s.emptyIcon}>♧</Text><Text style={s.emptyTitle}>No communities yet</Text><Text style={s.emptyText}>Create your first community and invite people to join.</Text></View>} renderItem={({item})=><Pressable style={s.card}><View style={s.communityIcon}><Text style={s.communityIconText}>{item.name.slice(0,2).toUpperCase()}</Text></View><View style={s.info}><Text style={s.name}>{item.name}</Text><Text style={s.description}>{item.description}</Text></View><Text style={s.chevron}>›</Text></Pressable>}/>
 <Modal visible={create} transparent animationType="slide" onRequestClose={()=>setCreate(false)}><View style={s.modal}><View style={s.sheet}><View style={s.sheetHandle}/><Text style={s.sheetTitle}>Create community</Text><Text style={s.label}>Community name</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. GG Creators" placeholderTextColor={MUTED} style={s.input}/><Text style={s.label}>Description</Text><TextInput value={description} onChangeText={setDescription} placeholder="What is this community about?" placeholderTextColor={MUTED} style={[s.input,s.multiline]} multiline/><Text style={s.helper}>You can invite members after creating it.</Text>{error?<Text style={s.error}>{error}</Text>:null}<Pressable style={[s.createButton,busy&&{opacity:.55}]} disabled={busy} onPress={createCommunity}><Text style={s.createText}>{busy?'Creating…':'Create community'}</Text></Pressable><Pressable style={s.cancel} onPress={()=>setCreate(false)}><Text style={s.cancelText}>Cancel</Text></Pressable></View></View></Modal>
 </SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BG},header:{height:72,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:20},back:{color:TEXT,fontSize:52,fontWeight:'200',width:42},title:{color:TEXT,fontSize:27,fontWeight:'900'},hero:{margin:20,padding:24,borderRadius:26,backgroundColor:CARD,borderWidth:1,borderColor:'#1c2d35',alignItems:'center'},heroIcon:{width:76,height:76,borderRadius:38,backgroundColor:'#073c2b',alignItems:'center',justifyContent:'center',marginBottom:14},heroIconText:{color:GREEN,fontSize:40},heroTitle:{color:TEXT,fontSize:24,fontWeight:'900',textAlign:'center'},heroText:{color:MUTED,fontSize:15,lineHeight:22,textAlign:'center',marginTop:8},createButton:{backgroundColor:GREEN,borderRadius:18,minHeight:54,paddingHorizontal:22,alignItems:'center',justifyContent:'center',marginTop:18},createText:{color:'#001b10',fontSize:16,fontWeight:'900'},sectionRow:{paddingHorizontal:22,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},section:{color:TEXT,fontSize:21,fontWeight:'900'},count:{color:GREEN,fontSize:16,fontWeight:'900'},list:{padding:14,paddingBottom:40},card:{backgroundColor:CARD,borderRadius:20,marginVertical:6,padding:15,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#17272f'},communityIcon:{width:58,height:58,borderRadius:18,backgroundColor:'#173b31',alignItems:'center',justifyContent:'center'},communityIconText:{color:GREEN,fontSize:16,fontWeight:'900'},info:{flex:1,marginLeft:14},name:{color:TEXT,fontSize:17,fontWeight:'900'},description:{color:MUTED,fontSize:13,marginTop:4},chevron:{color:MUTED,fontSize:30},empty:{alignItems:'center',paddingTop:50,paddingHorizontal:35},emptyIcon:{color:'#36505a',fontSize:55},emptyTitle:{color:TEXT,fontSize:20,fontWeight:'900',marginTop:12},emptyText:{color:MUTED,textAlign:'center',lineHeight:21,marginTop:7},modal:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.65)'},sheet:{backgroundColor:'#101c22',borderTopLeftRadius:28,borderTopRightRadius:28,padding:22,paddingBottom:30},sheetHandle:{width:48,height:5,borderRadius:3,backgroundColor:'#50616a',alignSelf:'center',marginBottom:16},sheetTitle:{color:TEXT,fontSize:25,fontWeight:'900',marginBottom:18},label:{color:'#c8d1d5',fontSize:13,fontWeight:'800',marginTop:9,marginBottom:7},input:{height:52,borderRadius:15,backgroundColor:'#18262d',borderWidth:1,borderColor:'#2a3b43',color:TEXT,paddingHorizontal:15,fontSize:16},multiline:{height:90,paddingTop:14,textAlignVertical:'top'},helper:{color:MUTED,fontSize:12,marginTop:10},error:{color:'#ff6b6b',fontSize:13,marginTop:8},cancel:{alignItems:'center',paddingVertical:14},cancelText:{color:TEXT,fontSize:16,fontWeight:'800'}});