import React,{useEffect,useState}from'react';
import{Alert,Modal,Pressable,Share,StyleSheet,Text,View}from'react-native';
import QRCode from'react-native-qrcode-svg';
import{supabase}from'./lib/supabase';
import{createConversationInvite,inviteLink}from'./lib/invites';

type Chat={id:string;name:string};
type Props={visible:boolean;onClose:()=>void;preferredConversationId?:string|null};
export default function InvitePeopleSheet({visible,onClose,preferredConversationId}:Props){
 const[chats,setChats]=useState<Chat[]>([]),[selected,setSelected]=useState<string|null>(preferredConversationId||null),[link,setLink]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!visible)return;setSelected(preferredConversationId||null);setLink('');(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:rows}=await supabase.from('conversation_members').select('conversation_id').eq('user_id',user.id);const ids=(rows||[]).map(x=>x.conversation_id);if(!ids.length){setChats([]);return}const{data}=await supabase.from('conversations').select('id,title,is_group').in('id',ids).eq('is_group',true).order('created_at',{ascending:false});setChats((data||[]).map(x=>({id:x.id,name:x.title||'GG Group'})));})()},[visible,preferredConversationId]);
 const makeInvite=async(id=selected)=>{if(!id){Alert.alert('Choose a group','Select a group or community first.');return}setBusy(true);try{const inv=await createConversationInvite(id);setLink(inviteLink(inv.token))}catch(e:any){Alert.alert('Invite failed',e?.message||String(e))}finally{setBusy(false)}};
 const share=async()=>{if(!link)return;await Share.share({message:`Join my GG group/community: ${link}`})};
 return <Modal transparent visible={visible} animationType="slide" onRequestClose={onClose}><View style={s.back}><View style={s.sheet}><View style={s.handle}/><View style={s.head}><Text style={s.title}>Add people</Text><Pressable onPress={onClose}><Text style={s.close}>×</Text></Pressable></View>
  {!link?<><Text style={s.sub}>Anyone in the group can invite people using a link or QR code.</Text><Text style={s.label}>Choose group or community</Text>{chats.length?<View style={s.list}>{chats.map(c=><Pressable key={c.id} onPress={()=>setSelected(c.id)} style={[s.choice,selected===c.id&&s.choiceActive]}><View style={s.icon}><Text style={s.iconText}>{c.name.slice(0,2).toUpperCase()}</Text></View><Text style={s.choiceText}>{c.name}</Text><Text style={s.check}>{selected===c.id?'✓':''}</Text></Pressable>)}</View>:<Text style={s.empty}>No group/community chats found yet.</Text>}<Pressable style={[s.primary,!selected&&{opacity:.5}]} disabled={!selected||busy} onPress={()=>makeInvite()}><Text style={s.primaryText}>{busy?'Creating…':'Create invite link'}</Text></Pressable></>:<><Text style={s.sub}>Share this link or let someone scan the QR code to join.</Text><View style={s.qr}><QRCode value={link} size={190} color="#061015" backgroundColor="#ffffff"/></View><Text selectable style={s.link}>{link}</Text><View style={s.actions}><Pressable style={s.share} onPress={share}><Text style={s.shareText}>↗ Share link</Text></Pressable><Pressable style={s.copy} onPress={()=>Alert.alert('Invite link',link)}><Text style={s.copyText}>Copy</Text></Pressable></View><Pressable style={s.secondary} onPress={()=>setLink('')}><Text style={s.secondaryText}>Create another invite</Text></Pressable></>}
 </View></View></Modal>;
}
const s=StyleSheet.create({back:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.7)'},sheet:{backgroundColor:'#101c22',borderTopLeftRadius:28,borderTopRightRadius:28,padding:22,paddingBottom:32,maxHeight:'90%'},handle:{width:48,height:5,borderRadius:3,backgroundColor:'#50616a',alignSelf:'center',marginBottom:16},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:'#f4f7f8',fontSize:25,fontWeight:'900'},close:{color:'#f4f7f8',fontSize:32},sub:{color:'#9fb0b8',fontSize:14,lineHeight:20,marginTop:8},label:{color:'#cbd5da',fontSize:13,fontWeight:'800',marginTop:18,marginBottom:8},list:{maxHeight:260},choice:{flexDirection:'row',alignItems:'center',padding:10,borderRadius:15,marginBottom:7,backgroundColor:'#17262d'},choiceActive:{borderWidth:1,borderColor:'#00e676',backgroundColor:'#123a2e'},icon:{width:44,height:44,borderRadius:14,backgroundColor:'#20483b',alignItems:'center',justifyContent:'center'},iconText:{color:'#00e676',fontWeight:'900'},choiceText:{color:'#f4f7f8',fontSize:15,fontWeight:'800',flex:1,marginLeft:12},check:{color:'#00e676',fontSize:22,fontWeight:'900'},empty:{color:'#9fb0b8',paddingVertical:20},primary:{height:54,borderRadius:17,backgroundColor:'#00e676',alignItems:'center',justifyContent:'center',marginTop:16},primaryText:{color:'#001b10',fontSize:16,fontWeight:'900'},qr:{alignSelf:'center',padding:14,backgroundColor:'#fff',borderRadius:18,marginTop:18},link:{color:'#d8e1e5',fontSize:13,textAlign:'center',marginTop:15,paddingHorizontal:10},actions:{flexDirection:'row',gap:10,marginTop:16},share:{flex:1,height:52,borderRadius:16,backgroundColor:'#00e676',alignItems:'center',justifyContent:'center'},shareText:{color:'#001b10',fontWeight:'900'},copy:{width:95,height:52,borderRadius:16,backgroundColor:'#1b2a31',alignItems:'center',justifyContent:'center'},copyText:{color:'#fff',fontWeight:'900'},secondary:{alignItems:'center',paddingVertical:16},secondaryText:{color:'#00e676',fontWeight:'800'}});