import React,{useEffect,useMemo,useState}from'react';
import{FlatList,Modal,Pressable,SafeAreaView,StatusBar,StyleSheet,Text,TextInput,View}from'react-native';
import{Conversation,loadConversations}from'./lib/conversations';
import MessengerHome from'./MessengerHome';
const BG='#0b1115',SEARCH='#20272c',TEXT='#f1f3f4',MUTED='#8d99a5',GREEN='#20d96b',LINE='#182127';
const SAMPLE=[
{name:'Fun and experience',message:'FavTech academy:  ◎  @  This gro...',time:'Yesterday',badge:'8'},
{name:'Ai smart trader Bot comm...',message:'~ Rider:  ◎  @  This group was me...',time:'Yesterday',badge:'20'},
{name:'Ella',message:'☎ Voice call',time:'Yesterday'},
{name:'Jamb 380 and Above',message:'Jamb, Waec and Postutme 1   ▶   أرجو...',time:''},
{name:'+234 817 239 8083',message:'✓✓ Can u deliver this Wednesday',time:'Yesterday'},
{name:'Baddy E',message:'✓✓ Startimes Rivers Main Office  ...',time:'Yesterday'},
{name:'FINANCIAL FREEDOM 13',message:'~ abrahamstephen587:  ▧  🔥 🔥 ...',time:''}
];
export default function PremiumMessengerHome(){
 const[chats,setChats]=useState<Conversation[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[search,setSearch]=useState(false),[menu,setMenu]=useState(false),[open,setOpen]=useState(false),[tab,setTab]=useState('Chats');
 const refresh=async()=>{setLoading(true);try{setChats(await loadConversations())}catch{}finally{setLoading(false)}};useEffect(()=>{refresh()},[]);
 const filtered=useMemo(()=>chats.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())),[chats,query]);
 const data:any[]=filtered.length?filtered:SAMPLE.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()));
 if(open)return <MessengerHome/>;
 const initials=(name:string)=>name.replace(/[^A-Za-z0-9]/g,'').slice(0,2).toUpperCase()||'GG';
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={BG}/>
  <View style={s.header}><Text style={s.title}>GG Messenger</Text><View style={s.headerActions}><Pressable onPress={()=>setSearch(v=>!v)} hitSlop={12}><Text style={s.headerIcon}>⌕</Text></Pressable><Pressable onPress={()=>setMenu(true)} hitSlop={12}><Text style={s.headerIcon}>⋮</Text></Pressable></View></View>
  <View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search chats" placeholderTextColor="#87939B" style={s.searchInput}/></View>
  <FlatList data={data} keyExtractor={(x,i)=>x.id||`${x.name}-${i}`} contentContainerStyle={s.list} refreshing={loading} onRefresh={refresh} renderItem={({item,index})=><Pressable style={s.chat} onPress={()=>filtered.length?setOpen(true):setOpen(true)}>
   <View style={[s.avatar,{backgroundColor:index===2?'#f4c92f':index===5?'#064d70':index===6?'#e9edf0':'#dce3ff'}]}><Text style={[s.avatarText,{color:index===2?'#6a4a00':index===5?'#48c9ff':'#173b66'}]}>{initials(item.name)}</Text></View>
   <View style={s.chatInfo}><View style={s.row}><Text numberOfLines={1} style={s.name}>{item.name}</Text><Text style={[s.time,{color:item.badge?GREEN:MUTED}]}>{item.time}</Text></View><View style={s.previewRow}><Text numberOfLines={1} style={s.preview}>{item.message||'No messages yet'}</Text>{item.badge&&<View style={s.badge}><Text style={s.badgeText}>{item.badge}</Text></View>}</View></View>
  </Pressable>}/>
  <Pressable style={s.fab} onPress={()=>setOpen(true)}><Text style={s.fabText}>＋</Text></Pressable>
  <View style={s.bottom}>{['Chats','Updates','Communities','Calls'].map((x,i)=><Pressable key={x} style={s.bottomItem} onPress={()=>setTab(x)}><View style={[s.iconPill,tab===x&&s.iconPillActive]}><Text style={[s.bottomIcon,tab===x&&s.active]}>{i===0?'▰':i===1?'◎':i===2?'♧':'⌕'}</Text>{x==='Chats'&&<View style={s.bottomBadge}><Text style={s.badgeText}>20</Text></View>}</View><Text style={[s.bottomText,tab===x&&s.active]}>{x}</Text></Pressable>)}</View>
  <Modal transparent visible={menu} animationType="fade" onRequestClose={()=>setMenu(false)}><Pressable style={s.modal} onPress={()=>setMenu(false)}><View style={s.menu}><Text style={s.menuTitle}>GG Messenger</Text><Pressable style={s.menuRow} onPress={()=>{setMenu(false);setOpen(true)}}><Text style={s.menuText}>New chat</Text></Pressable><Pressable style={s.menuRow} onPress={()=>setMenu(false)}><Text style={s.menuText}>Settings</Text></Pressable><Pressable style={s.menuRow} onPress={()=>setMenu(false)}><Text style={s.menuText}>Privacy & security</Text></Pressable></View></Pressable></Modal>
 </SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BG},header:{height:76,paddingHorizontal:24,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:TEXT,fontSize:29,fontWeight:'900',letterSpacing:-.7},headerActions:{flexDirection:'row',alignItems:'center',gap:22},headerIcon:{color:TEXT,fontSize:31,fontWeight:'500'},search:{marginHorizontal:22,marginTop:2,marginBottom:22,height:58,borderRadius:31,backgroundColor:SEARCH,flexDirection:'row',alignItems:'center',paddingHorizontal:18},searchIcon:{color:'#9aa5ad',fontSize:30},searchInput:{flex:1,color:TEXT,fontSize:18,marginLeft:10,fontWeight:'600'},list:{paddingBottom:105},chat:{minHeight:91,paddingHorizontal:22,flexDirection:'row',alignItems:'center'},avatar:{width:64,height:64,borderRadius:32,alignItems:'center',justifyContent:'center',marginRight:16},avatarText:{fontSize:20,fontWeight:'900'},chatInfo:{flex:1,height:76,justifyContent:'center',borderBottomWidth:1,borderBottomColor:LINE},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},name:{color:TEXT,fontSize:17,fontWeight:'800',flex:1,marginRight:10},time:{fontSize:12,fontWeight:'700'},previewRow:{flexDirection:'row',alignItems:'center',marginTop:5},preview:{color:MUTED,fontSize:14,flex:1,fontWeight:'600'},badge:{minWidth:28,height:28,paddingHorizontal:7,borderRadius:14,backgroundColor:GREEN,alignItems:'center',justifyContent:'center',marginLeft:8},badgeText:{color:'#061b10',fontSize:12,fontWeight:'900'},fab:{position:'absolute',right:22,bottom:91,width:64,height:64,borderRadius:20,backgroundColor:GREEN,alignItems:'center',justifyContent:'center',elevation:10},fabText:{color:'#061b10',fontSize:34,fontWeight:'500'},bottom:{position:'absolute',left:0,right:0,bottom:0,height:82,borderTopWidth:1,borderTopColor:LINE,backgroundColor:BG,flexDirection:'row',alignItems:'center',justifyContent:'space-around'},bottomItem:{alignItems:'center',width:'25%',position:'relative'},iconPill:{height:32,minWidth:56,borderRadius:18,alignItems:'center',justifyContent:'center'},iconPillActive:{backgroundColor:'#0b4b32'},bottomIcon:{color:'#e0e5e8',fontSize:23},active:{color:GREEN},bottomText:{color:'#e0e5e8',fontSize:12,fontWeight:'800',marginTop:4},bottomBadge:{position:'absolute',right:-4,top:-8,minWidth:21,height:21,borderRadius:11,backgroundColor:GREEN,alignItems:'center',justifyContent:'center'},modal:{flex:1,backgroundColor:'rgba(0,0,0,.55)',alignItems:'flex-end',paddingTop:55,paddingRight:14},menu:{width:225,borderRadius:14,backgroundColor:'#20282d',paddingVertical:8,elevation:10},menuTitle:{color:TEXT,fontSize:16,fontWeight:'900',paddingHorizontal:16,paddingVertical:10},menuRow:{paddingHorizontal:16,paddingVertical:14},menuText:{color:'#e9eff1',fontSize:15}});